import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/landing/Header';
import { Footer } from '@/components/landing/Footer';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { AuthProvider } from '@/components/authContext/Provider';
import StoreProvider from '@/components/storeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'OntoEmployee',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full`}>
        <div className="min-h-screen flex flex-col">
          <StoreProvider>
            <AuthProvider>
              {/* Header */}
              <Header />

              {/* Main Content */}
              <main className="flex-1">{children}</main>

              {/* Footer */}
              <Footer />

              {/* Toast Notifications */}
              <ToastContainer
                position="bottom-right"
                autoClose={5000}
                closeOnClick
              />
            </AuthProvider>
          </StoreProvider>
        </div>
      </body>
    </html>
  );
}
